In [ ]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/mhmmd-nauman/DataSets/master/wdbc/dsbc/csv/breast-cancer%20-%20complete.csv')

#del data['Unnamed: 32']

In [ ]:
index = data.index
number_of_rows = len(index)
print(number_of_rows)

286


In [ ]:
data.head()

Age menopause tumor-size inv-nodes  ... breast  breast-quad irradiat Class
0  30-39   premeno      30-34       0-2  ...   left     left_low       no     B
1  40-49   premeno      20-24       0-2  ...  right     right_up       no     B
2  40-49   premeno      20-24       0-2  ...   left     left_low       no     B
3  60-69      ge40      15-19       0-2  ...  right      left_up       no     B
4  40-49   premeno        0-4       0-2  ...  right    right_low       no     B

[5 rows x 10 columns]

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
data['Age'] = labelencoder_X_1.fit_transform(data['Age'])
data['menopause'] = labelencoder_X_1.fit_transform(data['menopause'])
data['tumor-size'] = labelencoder_X_1.fit_transform(data['tumor-size'])
data['inv-nodes'] = labelencoder_X_1.fit_transform(data['inv-nodes'])
data['node-caps'] = labelencoder_X_1.fit_transform(data['node-caps'])

data['deg-malig'] = labelencoder_X_1.fit_transform(data['deg-malig'])
data['breast'] = labelencoder_X_1.fit_transform(data['breast'])

data['breast-quad'] = labelencoder_X_1.fit_transform(data['breast-quad'])
data['irradiat'] = labelencoder_X_1.fit_transform(data['irradiat'])

y = labelencoder_X_1.fit_transform(data['Class'])

In [ ]:
X = data.iloc[:, 0:8].values

In [ ]:
X

array([[1, 2, 5, ..., 2, 0, 2],
       [2, 2, 3, ..., 1, 1, 5],
       [2, 2, 3, ..., 1, 0, 2],
       ...,
       [4, 0, 3, ..., 0, 1, 3],
       [2, 0, 5, ..., 2, 0, 2],
       [3, 0, 5, ..., 2, 0, 2]])

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
def create_baseline(x_size, y_size):
    # create model
    model = Sequential()
    model.add(Dense(18, input_dim=x_size, kernel_initializer='normal', activation='relu'))
    model.add(Dense(x_size,  activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model. We use the the logarithmic loss function, and the Adam gradient optimizer. mean_squared_error
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
    return model

In [ ]:
# Initialising the ANN
#classifier = Sequential()
model = create_baseline(X.shape[1], 1)

In [ ]:
# Adding the input layer and the first hidden layer
#classifier.add(Dense(3, activation='relu', input_dim=5))
# Adding dropout to prevent overfitting
#classifier.add(Dropout(p=0.1))

In [ ]:
# Adding the output layer
#classifier.add(Dense(1, activation='sigmoid'))

In [ ]:
# Compiling the ANN
#classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Fitting the ANN to the Training set
#classifier.fit(X_train, y_train, batch_size=10, epochs=50)
# Long scroll ahead but worth
# The batch size and number of epochs have been set using trial and error. Still looking for more efficient ways. Open to suggestions.
model.fit(X_train, y_train,
    batch_size=20,
    epochs=150,
    #shuffle=True,
    verbose=0 # Change it to 2, if wished to observe execution
    #validation_data=(kc_x_valid, kc_y_valid)
    ) 

In [ ]:
# Predicting the Test set results
#y_pred = classifier.predict(X_test)
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
#score = classifier.evaluate(X_test,y_test)
score = model.evaluate(X_test,y_test)
print(score)

3/3 [==============================] - 0s 3ms/step - loss: 0.2353 - accuracy: 0.6512
[0.23527227342128754, 0.6511628031730652]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
Sp = tn / (tn+fp)
Sn = tp/(tp + fn)

In [ ]:
print(cm)
print(Sp)
print(Sn)

[[51 11]
 [19  5]]
0.8225806451612904
0.20833333333333334


In [ ]:
from sklearn.metrics import cohen_kappa_score
cohen_score = cohen_kappa_score(y_test, y_pred)
print(cohen_score)

0.034431137724550864
