In [ ]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/mhmmd-nauman/DataSets/master/wdbc/csv/wdbc-complete.csv')

#del data['Unnamed: 32']

In [ ]:
index = data.index
number_of_rows = len(index)
print(number_of_rows)

569


In [ ]:
data.head()

Mean Radius  Mean Texture  ...  Worst Fractal Dimension  Diagnosis
0        17.99         10.38  ...                  0.11890          M
1        20.57         17.77  ...                  0.08902          M
2        19.69         21.25  ...                  0.08758          M
3        11.42         20.38  ...                  0.17300          M
4        20.29         14.34  ...                  0.07678          M

[5 rows x 31 columns]

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
#data['Application Status'] = labelencoder_X_1.fit_transform(data['Application Status'])
#data['Domicile'] = labelencoder_X_1.fit_transform(data['Domicile'])
#data['Gender'] = labelencoder_X_1.fit_transform(data['Gender'])
#data['Province'] = labelencoder_X_1.fit_transform(data['Province'])

y = labelencoder_X_1.fit_transform(data['Diagnosis'])

In [ ]:
X = data.iloc[:, 0:28].values

In [ ]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 6.656e-01, 7.119e-01,
        2.654e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.866e-01, 2.416e-01,
        1.860e-01],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 4.245e-01, 4.504e-01,
        2.430e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 3.094e-01, 3.403e-01,
        1.418e-01],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 8.681e-01, 9.387e-01,
        2.650e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 6.444e-02, 0.000e+00,
        0.000e+00]])

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
def create_baseline(x_size, y_size):
    # create model
    model = Sequential()
    model.add(Dense(36, input_dim=x_size, kernel_initializer='normal', activation='relu'))
    model.add(Dense(x_size,  activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model. We use the the logarithmic loss function, and the Adam gradient optimizer. mean_squared_error
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
    return model

In [ ]:
# Initialising the ANN
#classifier = Sequential()
model = create_baseline(X.shape[1], 1)

In [ ]:
# Adding the input layer and the first hidden layer
#classifier.add(Dense(3, activation='relu', input_dim=5))
# Adding dropout to prevent overfitting
#classifier.add(Dropout(p=0.1))

In [ ]:
# Adding the output layer
#classifier.add(Dense(1, activation='sigmoid'))

In [ ]:
# Compiling the ANN
#classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Fitting the ANN to the Training set
#classifier.fit(X_train, y_train, batch_size=10, epochs=50)
# Long scroll ahead but worth
# The batch size and number of epochs have been set using trial and error. Still looking for more efficient ways. Open to suggestions.
model.fit(X_train, y_train,
    batch_size=20,
    epochs=150,
    #shuffle=True,
    verbose=0 # Change it to 2, if wished to observe execution
    #validation_data=(kc_x_valid, kc_y_valid)
    ) 

In [ ]:
# Predicting the Test set results
#y_pred = classifier.predict(X_test)
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
#score = classifier.evaluate(X_test,y_test)
score = model.evaluate(X_test,y_test)
print(score)

6/6 [==============================] - 0s 2ms/step - loss: 0.0186 - accuracy: 0.9825
[0.018565263599157333, 0.9824561476707458]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
Sp = tn / (tn+fp)
Sn = tp/(tp + fn)

In [ ]:
print(cm)
print(Sp)
print(Sn)

[[106   2]
 [  1  62]]
0.9814814814814815
0.9841269841269841


In [ ]:
from sklearn.metrics import cohen_kappa_score
cohen_score = cohen_kappa_score(y_test, y_pred)
print(cohen_score)

0.962425840474621
