In [ ]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#data = pd.read_csv('https://raw.githubusercontent.com/mhmmd-nauman/DataSets/master/spring18/department-wise/department-wise-selected-features/Computer-science-Department.csv')
data = pd.read_csv('https://raw.githubusercontent.com/mhmmd-nauman/DataSets/master/spring18/department-wise/top15%20features/selected%20features/Computer-science-Department.csv')

#del data['Unnamed: 32']

In [ ]:
data.head()

Application Status    Domicile  ... English Marks Offered
0                 No        OPEN  ...             0      No
1           Complete  Bahawalpur  ...             0     Yes
2                 No  Bahawalpur  ...             0      No
3           Complete  Bahawalpur  ...             0      No
4                 No  Bahawalpur  ...             0      No

[5 rows x 10 columns]

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
data['Application Status'] = labelencoder_X_1.fit_transform(data['Application Status'])
data['Domicile'] = labelencoder_X_1.fit_transform(data['Domicile'])
data['Gender'] = labelencoder_X_1.fit_transform(data['Gender'])
data['Province'] = labelencoder_X_1.fit_transform(data['Province'])

y = labelencoder_X_1.fit_transform(data['Offered'])

In [ ]:
X = data.iloc[:, 0:9].values

In [ ]:
X

array([[   1,    1,    1, ...,  667,    0,    0],
       [   0,    0,    1, ..., 1100,    1,    0],
       [   1,    0,    1, ...,  825,    0,    0],
       ...,
       [   0,    1,    1, ...,  782,    0,    0],
       [   1,    1,    1, ...,  517,    0,    0],
       [   0,    1,    1, ...,  678,    0,    0]])

In [ ]:
y

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
y

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
def create_baseline(x_size, y_size):
    # create model
    model = Sequential()
    model.add(Dense(36, input_dim=x_size, kernel_initializer='normal', activation='relu'))
    model.add(Dense(x_size,  activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model. We use the the logarithmic loss function, and the Adam gradient optimizer. mean_squared_error
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
    return model

In [ ]:
# Initialising the ANN
#classifier = Sequential()
model = create_baseline(X.shape[1], 1)

In [ ]:
# Adding the input layer and the first hidden layer
#classifier.add(Dense(3, activation='relu', input_dim=5))
# Adding dropout to prevent overfitting
#classifier.add(Dropout(p=0.1))

In [ ]:
# Adding the output layer
#classifier.add(Dense(1, activation='sigmoid'))

In [ ]:
# Compiling the ANN
#classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Fitting the ANN to the Training set
#classifier.fit(X_train, y_train, batch_size=10, epochs=50)
# Long scroll ahead but worth
# The batch size and number of epochs have been set using trial and error. Still looking for more efficient ways. Open to suggestions.
model.fit(X_train, y_train,
    batch_size=20,
    epochs=150,
    #shuffle=True,
    verbose=0 # Change it to 2, if wished to observe execution
    #validation_data=(kc_x_valid, kc_y_valid)
    ) 

In [ ]:
# Predicting the Test set results
#y_pred = classifier.predict(X_test)
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
#score = classifier.evaluate(X_test,y_test)
score = model.evaluate(X_test,y_test)
print(score)

7/7 [==============================] - 0s 2ms/step - loss: 0.0164 - accuracy: 0.9773
[0.01644919067621231, 0.9772727489471436]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
Sp = tn / (tn+fp)
Sn = tp/(tp + fn)

In [ ]:
print(cm)
print(Sp)
print(Sn)

[[199   0]
 [  5  16]]
1.0
0.7619047619047619


In [ ]:
from sklearn.metrics import cohen_kappa_score
cohen_score = cohen_kappa_score(y_test, y_pred)
print(cohen_score)

0.8527048741296197
